/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IProxyInterface extends ethers.utils.Interface {
  functions: {
    "masterCopy()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "masterCopy",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "masterCopy", data: BytesLike): Result;

  events: {};
}

export class IProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IProxyInterface;

  functions: {
    masterCopy(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "masterCopy()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  masterCopy(overrides?: CallOverrides): Promise<string>;

  "masterCopy()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    masterCopy(overrides?: CallOverrides): Promise<string>;

    "masterCopy()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    masterCopy(overrides?: CallOverrides): Promise<BigNumber>;

    "masterCopy()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    masterCopy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "masterCopy()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
