/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IProxyCreationCallback } from "./IProxyCreationCallback";

export class IProxyCreationCallbackFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProxyCreationCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProxyCreationCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract GnosisSafeProxy",
        name: "proxy",
        type: "address",
      },
      {
        internalType: "address",
        name: "_singleton",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initializer",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "saltNonce",
        type: "uint256",
      },
    ],
    name: "proxyCreated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
