/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SafeBaalSummonerInterface extends ethers.utils.Interface {
  functions: {
    "SummonBaal(address,string,bytes,uint256)": FunctionFragment;
    "SummonBaalAndSafe(string,uint256,string,string,bytes[])": FunctionFragment;
    "baalCount()": FunctionFragment;
    "baalList(uint256)": FunctionFragment;
    "baalSingleton()": FunctionFragment;
    "baalType()": FunctionFragment;
    "baals(address)": FunctionFragment;
    "deployModule(address,bytes,uint256)": FunctionFragment;
    "gnosisFallbackLibrary()": FunctionFragment;
    "gnosisMultisendLibrary()": FunctionFragment;
    "gnosisSingleton()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "SummonBaal",
    values: [string, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SummonBaalAndSafe",
    values: [string, BigNumberish, string, string, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "baalCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baalList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "baalSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baalType", values?: undefined): string;
  encodeFunctionData(functionFragment: "baals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deployModule",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisFallbackLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisMultisendLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSingleton",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "SummonBaal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SummonBaalAndSafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baalCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baalList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baalSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baalType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisFallbackLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisMultisendLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisSingleton",
    data: BytesLike
  ): Result;

  events: {
    "ModuleProxyCreation(address,address)": EventFragment;
    "SummonedBaal(address,address,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ModuleProxyCreation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SummonedBaal"): EventFragment;
}

export class SafeBaalSummoner extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SafeBaalSummonerInterface;

  functions: {
    SummonBaal(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "SummonBaal(address,string,bytes,uint256)"(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    SummonBaalAndSafe(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "SummonBaalAndSafe(string,uint256,string,string,bytes[])"(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    baalCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "baalCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    baalList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "baalList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    baalSingleton(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "baalSingleton()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    baalType(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "baalType()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    baals(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "baals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    gnosisSingleton(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  SummonBaal(
    _avatar: string,
    _details: string,
    baalInitializer: BytesLike,
    _saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "SummonBaal(address,string,bytes,uint256)"(
    _avatar: string,
    _details: string,
    baalInitializer: BytesLike,
    _saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  SummonBaalAndSafe(
    _details: string,
    _saltNonce: BigNumberish,
    _name: string,
    _symbol: string,
    _baalInitializationActions: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "SummonBaalAndSafe(string,uint256,string,string,bytes[])"(
    _details: string,
    _saltNonce: BigNumberish,
    _name: string,
    _symbol: string,
    _baalInitializationActions: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  baalCount(overrides?: CallOverrides): Promise<BigNumber>;

  "baalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  baalList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "baalList(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  baalSingleton(overrides?: CallOverrides): Promise<string>;

  "baalSingleton()"(overrides?: CallOverrides): Promise<string>;

  baalType(overrides?: CallOverrides): Promise<string>;

  "baalType()"(overrides?: CallOverrides): Promise<string>;

  baals(arg0: string, overrides?: CallOverrides): Promise<string>;

  "baals(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  deployModule(
    masterCopy: string,
    initializer: BytesLike,
    saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployModule(address,bytes,uint256)"(
    masterCopy: string,
    initializer: BytesLike,
    saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  gnosisFallbackLibrary(overrides?: CallOverrides): Promise<string>;

  "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<string>;

  gnosisMultisendLibrary(overrides?: CallOverrides): Promise<string>;

  "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<string>;

  gnosisSingleton(overrides?: CallOverrides): Promise<string>;

  "gnosisSingleton()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SummonBaal(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "SummonBaal(address,string,bytes,uint256)"(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    SummonBaalAndSafe(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    "SummonBaalAndSafe(string,uint256,string,string,bytes[])"(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    baalCount(overrides?: CallOverrides): Promise<BigNumber>;

    "baalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    baalList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "baalList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    baalSingleton(overrides?: CallOverrides): Promise<string>;

    "baalSingleton()"(overrides?: CallOverrides): Promise<string>;

    baalType(overrides?: CallOverrides): Promise<string>;

    "baalType()"(overrides?: CallOverrides): Promise<string>;

    baals(arg0: string, overrides?: CallOverrides): Promise<string>;

    "baals(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<string>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<string>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<string>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<string>;

    gnosisSingleton(overrides?: CallOverrides): Promise<string>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ModuleProxyCreation(
      proxy: string | null,
      masterCopy: string | null
    ): EventFilter;

    SummonedBaal(
      baal: string | null,
      avatar: string | null,
      details: null,
      baalType: null
    ): EventFilter;
  };

  estimateGas: {
    SummonBaal(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "SummonBaal(address,string,bytes,uint256)"(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    SummonBaalAndSafe(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "SummonBaalAndSafe(string,uint256,string,string,bytes[])"(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    baalCount(overrides?: CallOverrides): Promise<BigNumber>;

    "baalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    baalList(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "baalList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baalSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    "baalSingleton()"(overrides?: CallOverrides): Promise<BigNumber>;

    baalType(overrides?: CallOverrides): Promise<BigNumber>;

    "baalType()"(overrides?: CallOverrides): Promise<BigNumber>;

    baals(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "baals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<BigNumber>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<BigNumber>;

    gnosisSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SummonBaal(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "SummonBaal(address,string,bytes,uint256)"(
      _avatar: string,
      _details: string,
      baalInitializer: BytesLike,
      _saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    SummonBaalAndSafe(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "SummonBaalAndSafe(string,uint256,string,string,bytes[])"(
      _details: string,
      _saltNonce: BigNumberish,
      _name: string,
      _symbol: string,
      _baalInitializationActions: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    baalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baalCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baalList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "baalList(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baalSingleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baalSingleton()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baalType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baalType()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baals(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "baals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    gnosisFallbackLibrary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gnosisFallbackLibrary()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gnosisMultisendLibrary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gnosisMultisendLibrary()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gnosisSingleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gnosisSingleton()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
